name: biof309
channels:
- bioconda
- conda-forge
- anaconda
- defaults
dependencies:
- altair=1.2.1=py_0
- asn1crypto=0.22.0=py36_0
- backports=1.0=py36_1
- backports.functools_lru_cache=1.5=py36_0
- biopython=1.70=py36_2
- bzip2=1.0.6=hd86a083_4
- blas=1.1=openblas
- bleach=2.0.0=py_1
- ca-certificates=2018.1.18=0
- certifi=2018.1.18=py36_0
- cffi=1.11.2=py36_0
- chardet=3.0.4=py36_0
- clangdev=5.0.0=default_0
- conda=4.4.11=py36_0
- conda-env=2.6.0=0
- curl=7.58.0=ha441bb4_0
- cryptography=2.1.4=py36_0
- cycler=0.10.0=py36_0
- dbus=1.10.22=0
- decorator=4.1.2=py36_0
- django=2.0.2=py36_0
- entrypoints=0.2.3=py36_1
- expat=2.2.5=0
- freetype=2.8.1=0
- gettext=0.19.8.1=0
- glib=2.55.0=0
- greenlet=0.4.13=py36_0
- html5lib=1.0.1=py_0
- icu=58.2=0
- idna=2.6=py36_1
- ipykernel=4.8.1=py36_0
- ipython=6.2.1=py36_1
- ipython_genutils=0.2.0=py36_0
- ipywidgets=7.1.2=py36_0
- jedi=0.11.1=py36_0
- jinja2=2.10=py36_0
- jpeg=9b=2
- jsonschema=2.6.0=py36_1
- jupyter=1.0.0=py36_0
- jupyter_client=5.2.2=py36_0
- jupyter_console=5.2.0=py36_0
- jupyter_core=4.4.0=py_0
- jupyterlab=0.31.8=py36_1
- jupyterlab_launcher=0.10.4=py36_0
- libcurl=7.58.0=hf30b1f0_0
- libcxx=5.0.0=0
- libcxxabi=4.0.1=hebd6815_0
- libedit=3.1.20170329=0
- libffi=3.2.1=3
- libiconv=1.15=0
- libpng=1.6.34=0
- libsodium=1.0.15=1
- libssh2=1.8.0=h322a93b_4
- libxml2=2.9.7=0
- llvm-meta=5.0.0=0
- llvmdev=5.0.0=default_1
- markupsafe=1.0=py36_0
- matplotlib=2.1.2=py36_0
- metakernel=0.20.14=py_0
- mistune=0.8.3=py_0
- msgpack-python=0.5.1=py36_0
- nbconvert=5.3.1=py_1
- nbformat=4.4.0=py36_0
- ncurses=5.9=10
- notebook=5.4.0=py36_0
- numpy=1.14.0=py36_blas_openblas_200
- openblas=0.2.20=7
- openssl=1.0.2n=0
- pandas=0.22.0=py36_0
- pandoc=2.1.1=0
- pandocfilters=1.4.1=py36_0
- parso=0.1.1=py_0
- pcre=8.39=0
- pexpect=4.4.0=py36_0
- pickleshare=0.7.4=py36_0
- pip=9.0.1=py36_1
- prompt_toolkit=1.0.15=py36_0
- psutil=5.4.0=py36_0
- ptyprocess=0.5.2=py36_0
- pycosat=0.6.3=py36_0
- pycparser=2.18=py36_0
- pygments=2.2.0=py36_0
- pyopenssl=17.4.0=py36_0
- pyparsing=2.2.0=py36_0
- pyqt=5.6.0=py36_4
- pysocks=1.6.8=py36_1
- python=3.6.4=0
- python-dateutil=2.6.1=py36_0
- pytz=2018.3=py_0
- pyzmq=17.0.0=py36_3
- qtconsole=4.3.1=py36_0
- readline=7.0=0
- requests=2.18.4=py36_1
- ruamel_yaml=0.11.14=py36_0
- samtools=1.7=1
- scikit-learn=0.19.1=py36_blas_openblas_201
- scipy=1.0.0=py36_blas_openblas_201
- send2trash=1.5.0=py_0
- setproctitle=1.1.10=py36_0
- setuptools=38.5.1=py36_0
- simplegeneric=0.8.1=py36_0
- sip=4.18=py36_1
- six=1.11.0=py36_1
- sqlite=3.20.1=2
- terminado=0.8.1=py36_0
- testpath=0.3.1=py36_0
- tk=8.6.7=0
- tornado=4.5.3=py36_0
- traitlets=4.3.2=py36_0
- urllib3=1.22=py36_0
- vega=0.4.4=py36_1
- wcwidth=0.1.7=py36_0
- webencodings=0.5=py36_0
- wheel=0.30.0=py36_2
- widgetsnbextension=3.1.4=py36_0
- xz=5.2.3=0
- zeromq=4.2.3=2
- zlib=1.2.11=0
- pip:
  - backports.functools-lru-cache==1.5
  - ipython-genutils==0.2.0
  - jupyter-client==5.2.2
  - jupyter-console==5.2.0
  - jupyter-core==4.4.0
  - jupyterlab-launcher==0.10.4
  - msgpack==0.5.4
  - prompt-toolkit==1.0.15
  - ruamel-yaml==0.11.14

